{% set name = "tinyarray" %}
{% set version = "1.2.3" %}
{% set sha256 = "47a06f801ed4b3d438f4f7098e244cd0c6d7db09428b1bc5ee813e52234dee9f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pytest
  run:
    - python

test:
  requires:
    - numpy
    - pytest
  source_files:
    - test_tinyarray.py
  commands:
    - py.test test_tinyarray.py
  imports:
    - tinyarray

about:
  home: http://git.kwant-project.org/tinyarray/about/
  license: BSD-2-Clause
  license_file: LICENSE.rst
  summary: Arrays of numbers for Python, optimized for small sizes
  description: |
    Tinyarrays are similar to NumPy arrays, but optimized for small sizes.
    Common operations on very small arrays are to 3-7 times faster than
    with NumPy (with NumPy 1.6 it used to be up to 35 times), and 3 times
    less memory is used to store them. Tinyarrays are useful if you need
    many small arrays of numbers, and cannot combine them into a few
    large ones.
  doc_url: https://gitlab.kwant-project.org/kwant/tinyarray

extra:
  recipe-maintainers:
    - basnijholt
    - akhmerov
